### ISSUE TITLE
exception 'Drupal\Core\Database\InvalidQueryException' with message 'Query condition 'taxonomy_term_data.uuid NOT IN ()' cannot be empty.' in                    [error]

### ISSUE THREAD

**Issue by marafa** [previousnext/drush_cmi_tools#25]
i am not sure but i do believe this is a bug in the cmi tools.

steps:
```
drush @$site -y config-import-plus --source=/home/$user/.drush/config-export
drush @$site import-all
```
the config-import-plus works without any discernible errors to the screen however the import-all always fails with
```
stdin: is not a tty
Importing taxonomies...
What import style would you like?
 [0]  :  Cancel 
 [1]  :  Full   
 [2]  :  Safe   
 [3]  :  Force
1
Using "Full" import style
Invalid argument supplied for foreach() TaxonomiesController.php:243                                                                                           [warning]
exception 'Drupal\Core\Database\InvalidQueryException' with message 'Query condition 'taxonomy_term_data.uuid NOT IN ()' cannot be empty.' in                    [error]
/home/$user/public_html/lab/core/lib/Drupal/Core/Database/Query/Condition.php:103
Stack trace:
#0 /home/$user/public_html/lab/core/lib/Drupal/Core/Database/Query/QueryConditionTrait.php(27):
Drupal\Core\Database\Query\Condition->condition('taxonomy_term_d...', Array, 'NOT IN')
#1 /home/$user/public_html/lab/core/lib/Drupal/Core/Entity/Query/Sql/Condition.php(53): Drupal\Core\Database\Query\Select->condition('taxonomy_term_d...',
Array, 'NOT IN')
#2 /home/$user/public_html/lab/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(163):
Drupal\Core\Entity\Query\Sql\Condition->compile(Object(Drupal\Core\Database\Driver\mysql\Select))
#3 /home/$user/public_html/lab/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(74): Drupal\Core\Entity\Query\Sql\Query->compile()
#4 /home/$user/public_html/lab/modules/structure_sync/src/Controller/TaxonomiesController.php(251): Drupal\Core\Entity\Query\Sql\Query->execute()
#5 /home/$user/public_html/lab/modules/structure_sync/src/Controller/TaxonomiesController.php(160):
Drupal\structure_sync\Controller\TaxonomiesController::deleteDeletedTaxonomies(NULL, Array)
#6 /home/$user/public_html/lab/modules/structure_sync/src/StructureSyncHelper.php(48):
Drupal\structure_sync\Controller\TaxonomiesController->importTaxonomies(Array, NULL)
#7 /home/$user/public_html/lab/modules/structure_sync/structure_sync.drush.inc(128): Drupal\structure_sync\StructureSyncHelper::importTaxonomies(Array)
#8 /home/$user/public_html/lab/modules/structure_sync/structure_sync.drush.inc(72): drush_structure_sync_import_taxonomies(false)
#9 [internal function]: drush_structure_sync_import_all()
#10 /home/$user/public_html/lab/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_structure...', Array)
#11 /home/$user/public_html/lab/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#12 [internal function]: drush_command()
#13 /home/$user/public_html/lab/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#14 /home/$user/public_html/lab/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#15 /home/$user/public_html/lab/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#16 /home/$user/public_html/lab/vendor/drush/drush/drush.php(12): drush_main()
#17 {main}
```

i do believe that it is borking on a missing config or an empty config

**Comment by larowlan** [comment]
`drush import-all` does not come from this module, looking at the stack trace, it looks to come from a module called structure_sync

**Comment by marafa** [comment]
agreed. however, it is borking on an empty field that was provided by this module. that is the reason i opened this issue

**Comment by larowlan** [comment]
this module doesn't provide fields.

the problem is structure_sync module.

http://cgit.drupalcode.org/structure_sync/tree/src/Controller/TaxonomiesController.php#n241

in that hunk `$uuidsInConfig` is empty.

personally, after reviewing that module, I wouldn't use it
